INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/ada_lovelace1.jpg', 1, 'Ritratto di Ada Byron, contessa di Lovelace di Alfred Edward Chalon, 1840');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/ada_lovelace2.jpg', 1, 'Ada Lovelace, incantatrice di numeri');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/ada_lovelace3.jpg', 1, 'Ritratto di Ada Lovelace');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/ada_lovelace4.jpg', 1, 'Il motore analitico di Charles Babbage, esposto allo Science Museum di Londra (maggio 2009)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/anita_borg1.jpg', 2, 'Foto di Anita Borg');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/anita_borg2.webp', 2, 'Il luogo di lavoro in cui Anita Borg lavorava sui sistemi operativi');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/anita_borg3.webp', 2, 'AnitaB.org riconosce i successi delle donne nel campo del informatica e le organizzazioni che ne riconoscono il valore attraverso una serie di premi.');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/anita_borg4.png', 2, 'Grace Hopper Celebration of Women in Computing');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/elizabeth_feinler1.jpg', 3, 'Foto di Elizabeth Feinler');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/elizabeth_feinler2.png', 3, 'Elizabeth "Jake" Feinler. Foto donata da Douglas Engelbart al Mouse Site, Università di Stanford.');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/elizabeth_feinler3.jpg', 3, 'Elizabeth Jake Feinler, oggi 89enne, quando era direttrice del Network Information Systems Center');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/elizabeth_feinler4,webp', 3, 'Elizabeth Feinler, membro della Internet Hall of Fame, che ha contribuito a creare Advanced Research Projects Agency Network (ARPANET), precursore del Internet di oggi');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marisa_bellisario1.jpg', 4, 'Foto di Maria Isabella Bellisario');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marisa_bellisario2.jpg', 4, 'Marisa viene assunta alla divisione elettronica della Olivetti');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marisa_bellisario3.jpg', 4, 'Il libro biografico: Donna & top manager. La mia storia');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marisa_bellisario4.jpg', 4, 'Direttrice generale di Italiel (gruppo STET)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/grace_hopper1.webp', 5, 'Foto di Grace Hopper in uniforme militare (Archivi della U.S. Navy)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/grace_hopper2.gif', 5, 'La falena ("bug") nel registro del Mark II (Foto storica del 1947, Harvard University Archives)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/grace_hopper3.jpg', 5, 'Esempio di codice COBOL (Screenshot da manuali vintage, es. Computer History Museum)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/grace_hopper4.jpg', 5, 'Medaglia presidenziale della Libertà (2016, postuma)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/joan_clarke1.jpg', 6, 'Joan Clarke, Fonte: Joan Clarke - la biografia di un enigma di Bletchley Park, 2019');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/joan_clarke2.jpg', 6, 'Principali successi: decifrazione di codici a Bletchley Park durante la seconda guerra mondiale');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/joan_clarke3.jpg', 6, 'Foto del team di Bletchley Park (Imperial War Museums)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/joan_clarke4.jpg', 6, 'Modello della macchina "Bombe" (Bletchley Park Museum Collections)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/mary_keller1.jpg', 7, 'Foto di Keller durante il dottorato (Archivi Clarke University)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/mary_keller2.webp', 7, 'Mary Kenneth Keller, la suora pioniera dell’informatica (Archivio delle suore della carità della beata vergine Maria)');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/mary_keller3.png', 7, ' Indica uno schema logico su una lavagna');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/mary_keller4.png', 7, 'Suor Keller, la prima donna ad ottenere un PhD in Informatica');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/margaret_hamilton1.jpg', 8, 'Margaret accanto alla pila di carta che conteneva tutto il codice dell’Apollo Guidance Computer ');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/margaret_hamilton2.webp', 8, 'Nel 2009, Margaret Hamilton e colleghi del MIT rifletterono sui loro contributi alle missioni Apollo, a 40 anni dallo sbarco lunare del Apollo 11 nel 1969');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/margaret_hamilton3.jpg', 8, 'Margaret premiata da Obama con la medaglia presidenziale alla libertà nel 2016');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/margaret_hamilton4.jpg', 8, 'Margaret Hamilton nel 1995');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marissa_mayer1.jpg', 9, 'Marissa Mayer: Simbolo di leadership femminile nel tech');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marissa_mayer2.webp', 9, 'CEO di Yahoo! (2012–2017');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marissa_mayer3.png', 9, 'Foto di Marissa mayer');
INSERT INTO IMMAGINI(URL, ID_DONNA, DESCRIZIONE) VALUES('immagini/marissa_mayer4.jpg', 9, 'Marissa Mayer, da volto femminile di Google a CEO di Yahoo!');