CREATE DATABASE DONNE;
USE DONNE;

CREATE TABLE UTENTI(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    COGNOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    AMMINISTRATORE TINYINT(1) NOT NULL,
    CHECK (AMMINISTRATORE=0 OR AMMINISTRATORE=1)
);

CREATE TABLE DONNE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    COGNOME VARCHAR(100) NOT NULL,
    DATA_NASCITA DATE NOT NULL,
    DESCRIZIONE TEXT NOT NULL
);

CREATE TABLE IMMAGINI(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    URL TEXT NOT NULL,
    ID_DONNA INT NOT NULL,
    DESCRIZIONE VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_DONNA) REFERENCES DONNE(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE UTENTI_DONNE(
    ID_UTENTE INT NOT NULL,
    ID_DONNA INT NOT NULL,
    PRIMARY KEY(ID_UTENTE,ID_DONNA),
    PREFERITI INT(1)
    CHECK (PREFERITI=0 OR PREFERITI=1),
    FOREIGN KEY(ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ID_DONNA) REFERENCES DONNE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ALTER TABLE UTENTI_DONNE DROP COLUMN COMMENTO;
-- ALTER TABLE UTENTI_DONNE DROP COLUMN VALUTAZIONE;

CREATE TABLE COMMENTI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_UTENTE INT NOT NULL,
    ID_DONNA INT NOT NULL,
    DATA_ORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALUTAZIONE INT(1),
    CHECK (VALUTAZIONE BETWEEN 1 AND 5),
    COMMENTO TEXT NOT NULL,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_DONNA) REFERENCES DONNE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);